# Generated by Django 5.2.5 on 2025-08-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='face_encodings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='student',
            name='photos_metadata',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
